# Generated by Django 5.2.8 on 2025-11-22 20:18

import django.core.validators
import django.db.models.deletion
import games.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, verbose_name='version')),
                ('wasm_file', models.FileField(blank=True, null=True, upload_to=games.models.game_wasm_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wasm'], message='Only WASM files are allowed.')], verbose_name='WASM file')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='games.game', verbose_name='game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='latest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest', to='games.gameversion'),
        ),
    ]
