# Generated by Django 5.2.8 on 2025-11-22 21:00

import django.db.models.deletion
import games.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_description_en_game_description_fr_game_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_folder', models.CharField(blank=True, default='', help_text="e.g. 'resources/music'. Leave empty for root.", max_length=1024, verbose_name='Target Folder')),
                ('file', models.FileField(upload_to=games.models.asset_file_path, verbose_name='Asset File')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='games.gameversion', verbose_name='Game Version')),
            ],
            options={
                'verbose_name': 'Asset File',
                'verbose_name_plural': 'Asset Files',
            },
        ),
    ]
