# Generated by Django 5.2.8 on 2025-11-26 12:11

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_assetfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.game_cover_directory_path, verbose_name='Cover Image'),
        ),
    ]
